# Generated by Django 5.2.7 on 2025-10-17 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summarizer', '0004_reminder'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='alcohol_consumption',
            field=models.CharField(blank=True, choices=[('None', 'None'), ('Socially', 'Socially'), ('Regularly', 'Regularly')], max_length=20),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='current_medications',
            field=models.TextField(blank=True, verbose_name='Current Medications & Dosages'),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='height',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Height (in cm)'),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='past_surgeries',
            field=models.TextField(blank=True, verbose_name='Past Surgeries or Major Illnesses'),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='smoking_status',
            field=models.CharField(blank=True, choices=[('Never', 'Never Smoked'), ('Former', 'Former Smoker'), ('Current', 'Current Smoker')], max_length=20),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='weight',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Weight (in kg)'),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='allergies',
            field=models.TextField(blank=True, verbose_name='Known Allergies (e.g., Penicillin, Peanuts)'),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='blood_group',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-'), ('Unknown', 'Unknown')], default='Unknown', max_length=10),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='contact_number',
            field=models.CharField(blank=True, max_length=15, verbose_name='Contact Number (e.g., +91...)'),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='emergency_contact_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Emergency Contact Name'),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, max_length=15, verbose_name='Emergency Contact Phone'),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='known_conditions',
            field=models.TextField(blank=True, verbose_name='Chronic Conditions (e.g., Diabetes, Hypertension)'),
        ),
    ]
