# Generated by Django 5.2.7 on 2025-10-17 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summarizer', '0005_patientprofile_alcohol_consumption_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='profile_picture',
            field=models.ImageField(default='default.jpg', upload_to='profile_pics'),
        ),
    ]
