# Generated by Django 5.2.7 on 2025-10-19 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summarizer', '0006_patientprofile_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientprofile',
            name='known_conditions',
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='chronic_conditions',
            field=models.TextField(blank=True, verbose_name='Chronic Conditions (e.g., Diabetes, Hypertension, Asthma)'),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='dietary_notes',
            field=models.TextField(blank=True, verbose_name='Dietary Restrictions or Notes (e.g., Vegetarian, Low Salt)'),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='family_medical_history',
            field=models.TextField(blank=True, verbose_name='Family Medical History (e.g., Heart disease, Cancer)'),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='immunization_history',
            field=models.TextField(blank=True, verbose_name='Immunization History (Vaccines received)'),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('Single', 'Single'), ('Married', 'Married'), ('Divorced', 'Divorced'), ('Widowed', 'Widowed')], max_length=20),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='occupation',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='past_major_illnesses',
            field=models.TextField(blank=True, verbose_name='Past Major Illnesses (e.g., Pneumonia, Jaundice)'),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='physician_contact',
            field=models.CharField(blank=True, max_length=20, verbose_name="Doctor's Contact"),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='primary_care_physician',
            field=models.CharField(blank=True, max_length=100, verbose_name="Primary Doctor's Name"),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='address',
            field=models.TextField(blank=True, verbose_name='Full Address'),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='allergies',
            field=models.TextField(blank=True, verbose_name='Known Allergies (Medications, Food, Environment)'),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='blood_group',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-'), ('Unknown', 'Unknown')], default='Unknown', max_length=10, verbose_name='Blood Group'),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='contact_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='Contact Number'),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Birth (YYYY-MM-DD)'),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Emergency Contact Phone'),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other'), ('Prefer not to say', 'Prefer not to say')], default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='height',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Height (cm)'),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='past_surgeries',
            field=models.TextField(blank=True, verbose_name='Past Surgeries (Include Year if possible)'),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='default.jpg', upload_to='profile_pics'),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Weight (kg)'),
        ),
    ]
