# Generated by Django 5.2.6 on 2026-06-05 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summarizer', '0007_remove_patientprofile_known_conditions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='last_reset_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reminder',
            name='last_sent',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reminder',
            name='taken_today',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='allergies',
            field=models.TextField(blank=True, verbose_name='Known Allergies'),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='chronic_conditions',
            field=models.TextField(blank=True, verbose_name='Chronic Conditions'),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='current_medications',
            field=models.TextField(blank=True, verbose_name='Current Medications'),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='dietary_notes',
            field=models.TextField(blank=True, verbose_name='Dietary Notes'),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='family_medical_history',
            field=models.TextField(blank=True, verbose_name='Family Medical History'),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='immunization_history',
            field=models.TextField(blank=True, verbose_name='Immunization History'),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='past_major_illnesses',
            field=models.TextField(blank=True, verbose_name='Past Major Illnesses'),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='past_surgeries',
            field=models.TextField(blank=True, verbose_name='Past Surgeries'),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='smoking_status',
            field=models.CharField(blank=True, choices=[('Never', 'Never'), ('Former', 'Former'), ('Current', 'Current')], max_length=20),
        ),
    ]
