# Generated by Django 5.2.6 on 2026-06-05 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summarizer', '0008_reminder_last_reset_date_reminder_last_sent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='ai_consultations_used',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='is_premium',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='level',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
